version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: q1wertyu
      POSTGRES_DB: db_name
